# Generated by Django 2.0.7 on 2018-07-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employeePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_employee', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('websiteURL', models.CharField(max_length=100)),
                ('publisheddate', models.DateField(verbose_name='Published Date')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
